# coding=utf-8
# Copyright 2026 The Alibaba Qwen team.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from dataclasses import dataclass
from difflib import SequenceMatcher
import logging
import re
from typing import Any, Dict, List, Optional, Tuple, Union
import unicodedata

import numpy as np
import torch
from qwen_asr.core.transformers_backend import (
    Qwen3ASRConfig,
    Qwen3ASRForConditionalGeneration,
    Qwen3ASRProcessor,
)
from transformers import AutoConfig, AutoModel, AutoProcessor

AutoConfig.register("qwen3_asr", Qwen3ASRConfig)
AutoModel.register(Qwen3ASRConfig, Qwen3ASRForConditionalGeneration)
AutoProcessor.register(Qwen3ASRConfig, Qwen3ASRProcessor)

from .qwen3_forced_aligner import Qwen3ForcedAligner
from .utils import (
    MAX_ASR_INPUT_SECONDS,
    MAX_FORCE_ALIGN_INPUT_SECONDS,
    SAMPLE_RATE,
    SUPPORTED_LANGUAGES,
    AudioChunk,
    AudioLike,
    chunk_list,
    merge_languages,
    normalize_audios,
    normalize_language_name,
    parse_asr_output,
    split_audio_into_chunks,
    validate_language,
)

try:
    from qwen_asr.core.vllm_backend import Qwen3ASRForConditionalGeneration
    from vllm import ModelRegistry
    ModelRegistry.register_model("Qwen3ASRForConditionalGeneration", Qwen3ASRForConditionalGeneration)
except:
    pass

try:
    from rapidfuzz import fuzz as rapidfuzz_fuzz
except Exception:
    rapidfuzz_fuzz = None

try:
    from pypinyin import lazy_pinyin
except Exception:
    lazy_pinyin = None


logger = logging.getLogger(__name__)

_PUNCT_OR_SPACE_RE = re.compile(r"[\W_]+", re.UNICODE)
_CJK_RE = re.compile(r"[\u3400-\u4dbf\u4e00-\u9fff\uf900-\ufaff]")
TIMESTAMP_ASR_CHUNK_SECONDS = 45.0


@dataclass
class ASRTranscription:
    """
    One transcription result.

    Attributes:
        language (str):
            Merged language string for the sample, e.g. "Chinese" or "Chinese,English".
            Empty string if unknown or silent audio.
        text (str):
            Transcribed text.
        time_stamps (Optional[Any]):
            Forced aligner output (ForcedAlignResult).
            Present only when return_time_stamps=True.
    """
    language: str
    text: str
    time_stamps: Optional[Any] = None
    source_text: Optional[str] = None
    source_time_stamps: Optional[Any] = None


@dataclass
class ASRStreamingState:
    """
    Streaming ASR state for one audio stream (single utterance).

    Attributes:
        unfixed_chunk_num (int):
            For the first N chunks, do not use previous ASR result as prefix prompt (reset prefix to "").
        unfixed_token_num (int):
            When chunk_id >= unfixed_chunk_num, rollback the last K tokens from the accumulated text
            before using it as prefix prompt, to reduce boundary jitter.
        chunk_size_sec (float):
            Chunk size in seconds. Audio will be fed to the model in increments of this length.
        chunk_size_samples (int):
            Chunk size in samples at 16kHz (derived from chunk_size_sec).
        chunk_id (int):
            Current chunk index (0-based).
        buffer (np.ndarray):
            Buffered PCM samples that are not yet consumed into a full chunk.
        audio_accum (np.ndarray):
            Accumulated audio from the beginning of the stream up to current time (no padding).
        prompt_raw (str):
            Base prompt generated by chat template (with generation prompt), without appended prefix text.
        context (str):
            Context string.
        force_language (Optional[str]):
            If provided, force output to be text-only by appending "language X<asr_text>" in prompt_raw,
            consistent with non-streaming transcribe().
        language (str):
            Latest parsed language (updated after each chunk decode). Empty if unknown/silent.
        text (str):
            Latest parsed transcription text (updated after each chunk decode).
        _raw_decoded (str):
            Internal accumulated decoded raw text (before parse_asr_output normalization).
            Used for rollback/token trimming and as prefix for prompting.
    """
    unfixed_chunk_num: int
    unfixed_token_num: int
    chunk_size_sec: float
    chunk_size_samples: int

    chunk_id: int
    buffer: np.ndarray
    audio_accum: np.ndarray

    prompt_raw: str
    context: str
    force_language: Optional[str]

    language: str
    text: str
    _raw_decoded: str


class Qwen3ASRModel:
    """
    Unified inference wrapper for Qwen3-ASR with two backends:
      - Transformers backend 
      - vLLM backend

    It optionally supports time stamp output via Qwen3-ForcedAligner.

    Notes:
      - Each request uses a context text and exactly one audio.
      - If language is provided, the prompt will force the output to be text-only by appending
        "language {Language}<asr_text>" to the assistant prompt.
    """

    def __init__(
        self,
        backend: str,
        model: Any,
        processor: Any,
        sampling_params: Optional[Any] = None,
        forced_aligner: Optional[Qwen3ForcedAligner] = None,
        max_inference_batch_size: int = -1,
        max_new_tokens: int = 512,
    ):
        self.backend = backend  # "transformers" | "vllm"
        self.model = model
        self.processor = processor
        self.sampling_params = sampling_params
        self.forced_aligner = forced_aligner
        self.max_inference_batch_size = int(max_inference_batch_size)
        self.max_new_tokens = max_new_tokens

        if backend == "transformers":
            self.device = getattr(model, "device", None)
            if self.device is None:
                try:
                    self.device = next(model.parameters()).device
                except StopIteration:
                    self.device = torch.device("cpu")
            self.dtype = getattr(model, "dtype", torch.float32)
        else:
            self.device = None
            self.dtype = None

    @classmethod
    def from_pretrained(
        cls,
        pretrained_model_name_or_path: str,
        forced_aligner: Optional[str] = None,
        forced_aligner_kwargs: Optional[Dict[str, Any]] = None,
        max_inference_batch_size: int = 32,
        max_new_tokens: Optional[int] = 512,
        **kwargs,
    ) -> "Qwen3ASRModel":
        """
        Initialize using Transformers backend.

        Args:
            pretrained_model_name_or_path:
                HuggingFace repo id or local directory.
            forced_aligner:
                Optional forced aligner model path/repo id.
            forced_aligner_kwargs:
                Optional kwargs forwarded to Qwen3ForcedAligner.from_pretrained(...).
            max_inference_batch_size:
                Batch size limit for inference. -1 means no chunking. Small values can avoid OOM.
            max_new_tokens:
                Maximum number of tokens to generate.
            **kwargs:
                Forwarded to AutoModel.from_pretrained(...).

        Returns:
            Qwen3ASRModel
        """

        model = AutoModel.from_pretrained(pretrained_model_name_or_path, **kwargs)

        processor = AutoProcessor.from_pretrained(pretrained_model_name_or_path, fix_mistral_regex=True)

        forced_aligner_model = None
        if forced_aligner is not None:
            forced_aligner_model = Qwen3ForcedAligner.from_pretrained(
                forced_aligner, **(forced_aligner_kwargs or {})
            )

        return cls(
            backend="transformers",
            model=model,
            processor=processor,
            sampling_params=None,
            forced_aligner=forced_aligner_model,
            max_inference_batch_size=max_inference_batch_size,
            max_new_tokens=max_new_tokens,
        )

    @classmethod
    def LLM(
        cls,
        model: str,
        forced_aligner: Optional[str] = None,
        forced_aligner_kwargs: Optional[Dict[str, Any]] = None,
        max_inference_batch_size: int = -1,
        max_new_tokens: Optional[int] = 4096,
        **kwargs,
    ) -> "Qwen3ASRModel":
        """
        Initialize using vLLM backend.

        Import is isolated to keep vLLM optional.

        Args:
            model:
                Model path/repo for vLLM.
            forced_aligner:
                Optional forced aligner model path/repo id.
            forced_aligner_kwargs:
                Optional kwargs forwarded to Qwen3ForcedAligner.from_pretrained(...).
            max_inference_batch_size:
                Batch size limit for inference. -1 means no chunking. Small values can avoid OOM.
            max_new_tokens:
                Maximum number of tokens to generate.
            **kwargs:
                Forwarded to vllm.LLM(...).

        Returns:
            Qwen3ASRModel

        Raises:
            ImportError: If vLLM is not installed.
        """
        try:
            from vllm import LLM as vLLM
            from vllm import SamplingParams
        except Exception as e:
            raise ImportError(
                "vLLM is not available. Install with: pip install qwen-asr[vllm]"
            ) from e

        llm = vLLM(model=model, **kwargs)

        processor = Qwen3ASRProcessor.from_pretrained(model, fix_mistral_regex=True)
        sampling_params = SamplingParams(**({"temperature": 0.0, "max_tokens": max_new_tokens}))

        forced_aligner_model = None
        if forced_aligner is not None:
            forced_aligner_model = Qwen3ForcedAligner.from_pretrained(
                forced_aligner, **(forced_aligner_kwargs or {})
            )

        return cls(
            backend="vllm",
            model=llm,
            processor=processor,
            sampling_params=sampling_params,
            forced_aligner=forced_aligner_model,
            max_inference_batch_size=max_inference_batch_size,
            max_new_tokens=None,
        )

    def get_supported_languages(self) -> List[str]:
        """
        Returns the supported language list.

        Returns:
            List[str]: Canonical language names.
        """
        return list(SUPPORTED_LANGUAGES)

    @torch.no_grad()
    def transcribe(
        self,
        audio: Union[AudioLike, List[AudioLike]],
        context: Union[str, List[str]] = "",
        language: Optional[Union[str, List[Optional[str]]]] = None,
        return_time_stamps: bool = False,
    ) -> List[ASRTranscription]:
        """
        Transcribe audio with optional context and optional forced alignment timestamps.

        Args:
            audio:
                Audio input(s). Supported:
                  - str: local path / URL / base64 data url
                  - (np.ndarray, sr)
                  - list of above
            context:
                Context string(s). If scalar, it will be broadcast to batch size.
            language:
                Optional language(s). If provided, it must be in supported languages.
                If scalar, it will be broadcast to batch size.
                If provided, the prompt will force output to be transcription text only.
            return_time_stamps:
                If True, timestamps are produced via forced aligner and merged across chunks.
                This requires forced_aligner initialized.

        Returns:
            List[ASRTranscription]: One result per input audio.

        Raises:
            ValueError:
                - If return_time_stamps=True but forced_aligner is not provided.
                - If language is unsupported.
                - If batch sizes mismatch for context/language.
        """
        if return_time_stamps and self.forced_aligner is None:
            raise ValueError("return_time_stamps=True requires `forced_aligner` to be provided at initialization.")

        wavs = normalize_audios(audio)
        n = len(wavs)

        ctxs = context if isinstance(context, list) else [context]
        if len(ctxs) == 1 and n > 1:
            ctxs = ctxs * n
        if len(ctxs) != n:
            raise ValueError(f"Batch size mismatch: audio={n}, context={len(ctxs)}")

        langs_in: List[Optional[str]]
        if language is None:
            langs_in = [None] * n
        else:
            langs_in = language if isinstance(language, list) else [language]
            if len(langs_in) == 1 and n > 1:
                langs_in = langs_in * n
            if len(langs_in) != n:
                raise ValueError(f"Batch size mismatch: audio={n}, language={len(langs_in)}")

        langs_norm: List[Optional[str]] = []
        for l in langs_in:
            if l is None or str(l).strip() == "":
                langs_norm.append(None)
            else:
                ln = normalize_language_name(str(l))
                validate_language(ln)
                langs_norm.append(ln)

        max_chunk_sec = (
            min(float(MAX_FORCE_ALIGN_INPUT_SECONDS), TIMESTAMP_ASR_CHUNK_SECONDS)
            if return_time_stamps
            else MAX_ASR_INPUT_SECONDS
        )

        # chunk audios and record mapping
        chunks: List[AudioChunk] = []
        for i, wav in enumerate(wavs):
            parts = split_audio_into_chunks(
                wav=wav,
                sr=SAMPLE_RATE,
                max_chunk_sec=max_chunk_sec,
            )
            for j, (cwav, offset_sec) in enumerate(parts):
                chunks.append(AudioChunk(orig_index=i, chunk_index=j, wav=cwav, sr=SAMPLE_RATE, offset_sec=offset_sec))

        # run ASR on chunks
        chunk_ctx: List[str] = [ctxs[c.orig_index] for c in chunks]
        chunk_lang: List[Optional[str]] = [langs_norm[c.orig_index] for c in chunks]
        chunk_wavs: List[np.ndarray] = [c.wav for c in chunks]
        raw_outputs = self._infer_asr(chunk_ctx, chunk_wavs, chunk_lang)

        # parse outputs, prepare for optional alignment
        per_chunk_lang: List[str] = []
        per_chunk_text: List[str] = []
        for out, forced_lang in zip(raw_outputs, chunk_lang):
            lang, txt = parse_asr_output(out, user_language=forced_lang)
            per_chunk_lang.append(lang)
            per_chunk_text.append(txt)

        # forced alignment (optional)
        per_chunk_align: List[Optional[Any]] = [None] * len(chunks)
        if return_time_stamps:
            to_align_audio = []
            to_align_text = []
            to_align_lang = []
            to_align_idx = []

            for idx, (c, txt, lang_pred) in enumerate(zip(chunks, per_chunk_text, per_chunk_lang)):
                if txt.strip() == "":
                    continue
                to_align_audio.append((c.wav, c.sr))
                to_align_text.append(txt)
                to_align_lang.append(lang_pred)
                to_align_idx.append(idx)

            # batch align with max_inference_batch_size
            aligned_results: List[Any] = []
            for a_chunk, t_chunk, l_chunk in zip(
                chunk_list(to_align_audio, self.max_inference_batch_size),
                chunk_list(to_align_text, self.max_inference_batch_size),
                chunk_list(to_align_lang, self.max_inference_batch_size),
            ):
                aligned_results.extend(
                    self.forced_aligner.align(audio=a_chunk, text=t_chunk, language=l_chunk)
                )

            # offset fix
            for k, idx in enumerate(to_align_idx):
                c = chunks[idx]
                r = aligned_results[k]
                per_chunk_align[idx] = self._offset_align_result(r, c.offset_sec)

        # merge chunks back to original samples
        out_langs: List[List[str]] = [[] for _ in range(n)]
        out_texts: List[List[str]] = [[] for _ in range(n)]
        out_aligns: List[List[Any]] = [[] for _ in range(n)]

        for c, lang, txt, al in zip(chunks, per_chunk_lang, per_chunk_text, per_chunk_align):
            out_langs[c.orig_index].append(lang)
            out_texts[c.orig_index].append(txt)
            if return_time_stamps and al is not None:
                out_aligns[c.orig_index].append(al)

        results: List[ASRTranscription] = []
        for i in range(n):
            merged_text = "".join([t for t in out_texts[i] if t is not None])
            merged_language = merge_languages(out_langs[i])
            merged_align = None
            if return_time_stamps:
                merged_align = self._merge_align_results(out_aligns[i])
            results.append(ASRTranscription(language=merged_language, text=merged_text, time_stamps=merged_align))

        return results

    @torch.no_grad()
    def align_ground_truth(
        self,
        audio: Union[AudioLike, List[AudioLike]],
        ground_truth_text: Union[str, List[str]],
        context: Union[str, List[str]] = "",
        language: Optional[Union[str, List[Optional[str]]]] = None,
    ) -> List[ASRTranscription]:
        """
        Align externally provided reference text to audio.

        For long audio, this method reuses chunk-level ASR output as a monotonic anchor pass,
        assigns a chunk-local slice of the reference text to each audio chunk, then runs the
        forced aligner on those chunk-local reference slices and merges the timestamp results.
        """
        if self.forced_aligner is None:
            raise ValueError("align_ground_truth() requires `forced_aligner` to be provided at initialization.")

        wavs = normalize_audios(audio)
        n = len(wavs)

        refs = ground_truth_text if isinstance(ground_truth_text, list) else [ground_truth_text]
        if len(refs) == 1 and n > 1:
            refs = refs * n
        if len(refs) != n:
            raise ValueError(f"Batch size mismatch: audio={n}, ground_truth_text={len(refs)}")

        ctxs = context if isinstance(context, list) else [context]
        if len(ctxs) == 1 and n > 1:
            ctxs = ctxs * n
        if len(ctxs) != n:
            raise ValueError(f"Batch size mismatch: audio={n}, context={len(ctxs)}")

        langs_in: List[Optional[str]]
        if language is None:
            langs_in = [None] * n
        else:
            langs_in = language if isinstance(language, list) else [language]
            if len(langs_in) == 1 and n > 1:
                langs_in = langs_in * n
            if len(langs_in) != n:
                raise ValueError(f"Batch size mismatch: audio={n}, language={len(langs_in)}")

        langs_norm: List[Optional[str]] = []
        for l in langs_in:
            if l is None or str(l).strip() == "":
                langs_norm.append(None)
            else:
                ln = normalize_language_name(str(l))
                validate_language(ln)
                langs_norm.append(ln)

        asr_results = self.transcribe(
            audio=[(wav, SAMPLE_RATE) for wav in wavs],
            context=ctxs,
            language=langs_norm,
            return_time_stamps=True,
        )

        out_aligns: List[List[Any]] = [[] for _ in range(n)]
        out_langs: List[List[str]] = [[] for _ in range(n)]

        for i in range(n):
            asr_result = asr_results[i]
            resolved_language = self._resolve_alignment_language([asr_result.language], langs_norm[i])
            if asr_result.language:
                out_langs[i].append(asr_result.language)

            reference = str(refs[i] or "").strip()
            if not reference:
                continue

            asr_items = list(getattr(asr_result.time_stamps, "items", []) or [])
            if not asr_items:
                self._log_ground_truth_alignment(
                    "warning",
                    f"sample={i} ASR transcription produced 0 timestamp items; cannot correct ground truth.",
                )
                continue

            self._log_ground_truth_alignment(
                "info",
                f"sample={i} asr items={len(asr_items)} time_range={round(float(asr_items[0].start_time), 3)}-{round(float(asr_items[-1].end_time), 3)} "
                f"pred_preview='{self._preview_text(asr_result.text)}'.",
            )
            self._log_text_sentences_with_item_times(
                sample_idx=i,
                label="asr",
                text=asr_result.text,
                language=resolved_language,
                items=asr_items,
            )

            gt_aligned_result = self._align_reference_to_asr_timestamps(
                reference_text=reference,
                language=resolved_language,
                asr_aligned_results=[asr_result.time_stamps],
                sample_idx=i,
            )
            if gt_aligned_result is None:
                self._log_ground_truth_alignment(
                    "warning",
                    f"sample={i} global GT alignment via ASR timestamps produced no result.",
                )
            else:
                out_aligns[i].append(gt_aligned_result)
                item_count = len(getattr(gt_aligned_result, "items", []) or [])
                self._log_ground_truth_alignment(
                    "info",
                    f"sample={i} corrected_gt_tokens={item_count}.",
                )
                self._log_text_sentences_with_item_times(
                    sample_idx=i,
                    label="gt",
                    text=reference,
                    language=resolved_language,
                    items=list(getattr(gt_aligned_result, "items", []) or []),
                )

        results: List[ASRTranscription] = []
        for i in range(n):
            merged_language = merge_languages(out_langs[i])
            if not merged_language:
                merged_language = langs_norm[i] or ""
            merged_align = self._merge_align_results(out_aligns[i])
            results.append(
                ASRTranscription(
                    language=merged_language,
                    text=str(refs[i] or ""),
                    time_stamps=merged_align,
                    source_text=getattr(asr_result, "text", None),
                    source_time_stamps=getattr(asr_result, "time_stamps", None),
                )
            )

        return results

    @torch.no_grad()
    def align_ground_truth_direct(
        self,
        audio: Union[AudioLike, List[AudioLike]],
        ground_truth_text: Union[str, List[str]],
        context: Union[str, List[str]] = "",
        language: Optional[Union[str, List[Optional[str]]]] = None,
        max_force_align_input_seconds: float = 360.0,
    ) -> List[ASRTranscription]:
        """
        Align externally provided reference text to whole audio directly, without chunking.

        This is useful when the reference transcript is trusted and the audio is short enough
        to fit in one forced-alignment request.
        """
        if self.forced_aligner is None:
            raise ValueError("align_ground_truth_direct() requires `forced_aligner` to be provided at initialization.")

        wavs = normalize_audios(audio)
        n = len(wavs)

        refs = ground_truth_text if isinstance(ground_truth_text, list) else [ground_truth_text]
        if len(refs) == 1 and n > 1:
            refs = refs * n
        if len(refs) != n:
            raise ValueError(f"Batch size mismatch: audio={n}, ground_truth_text={len(refs)}")

        ctxs = context if isinstance(context, list) else [context]
        if len(ctxs) == 1 and n > 1:
            ctxs = ctxs * n
        if len(ctxs) != n:
            raise ValueError(f"Batch size mismatch: audio={n}, context={len(ctxs)}")

        langs_in: List[Optional[str]]
        if language is None:
            langs_in = [None] * n
        else:
            langs_in = language if isinstance(language, list) else [language]
            if len(langs_in) == 1 and n > 1:
                langs_in = langs_in * n
            if len(langs_in) != n:
                raise ValueError(f"Batch size mismatch: audio={n}, language={len(langs_in)}")

        langs_norm: List[Optional[str]] = []
        for l in langs_in:
            if l is None or str(l).strip() == "":
                langs_norm.append(None)
            else:
                ln = normalize_language_name(str(l))
                validate_language(ln)
                langs_norm.append(ln)

        max_seconds = float(max_force_align_input_seconds)
        if max_seconds <= 0:
            raise ValueError(
                f"max_force_align_input_seconds must be > 0, got: {max_force_align_input_seconds}"
            )

        to_align_audio: List[Tuple[np.ndarray, int]] = []
        to_align_text: List[str] = []
        to_align_lang: List[str] = []
        out_languages: List[str] = []

        for i, (wav, ref_text, forced_lang) in enumerate(zip(wavs, refs, langs_norm)):
            duration_sec = float(wav.shape[0]) / float(SAMPLE_RATE)
            if duration_sec > max_seconds:
                raise ValueError(
                    "align_ground_truth_direct() does not chunk audio. "
                    f"Sample {i} is {duration_sec:.3f}s, which exceeds max_force_align_input_seconds={max_seconds:.3f}."
                )

            resolved_language = self._resolve_alignment_language([], forced_lang)
            out_languages.append(resolved_language)

            ref_text = str(ref_text or "").strip()
            if not ref_text:
                self._log_ground_truth_alignment(
                    "warning",
                    f"sample={i} direct alignment skipped because ground_truth_text is empty.",
                )
                to_align_audio.append((wav, SAMPLE_RATE))
                to_align_text.append("")
                to_align_lang.append(resolved_language)
                continue

            self._log_ground_truth_alignment(
                "info",
                f"sample={i} direct alignment duration={round(duration_sec, 3)}s "
                f"max_force_align_input_seconds={round(max_seconds, 3)} ref_preview='{self._preview_text(ref_text)}'.",
            )
            to_align_audio.append((wav, SAMPLE_RATE))
            to_align_text.append(ref_text)
            to_align_lang.append(resolved_language)

        aligned_results = self.forced_aligner.align(
            audio=to_align_audio,
            text=to_align_text,
            language=to_align_lang,
        )

        results: List[ASRTranscription] = []
        for i, (ref_text, lang, aligned) in enumerate(zip(refs, out_languages, aligned_results)):
            item_count = len(getattr(aligned, "items", []) or [])
            self._log_ground_truth_alignment(
                "info",
                f"sample={i} direct alignment produced {item_count} timestamp items.",
            )
            results.append(
                ASRTranscription(
                    language=lang,
                    text=str(ref_text or ""),
                    time_stamps=aligned,
                )
            )

        return results

    def _build_messages(self, context: str, audio_payload: Any) -> List[Dict[str, Any]]:
        return [
            {"role": "system", "content": context or ""},
            {"role": "user", "content": [{"type": "audio", "audio": audio_payload}]},
        ]

    def _build_text_prompt(self, context: str, force_language: Optional[str]) -> str:
        """
        Build the string prompt for one request.

        If force_language is provided, "language X<asr_text>" is appended after the generation prompt
        to request text-only output.
        """
        msgs = self._build_messages(context=context, audio_payload="")
        base = self.processor.apply_chat_template(msgs, add_generation_prompt=True, tokenize=False)
        if force_language:
            base = base + f"language {force_language}{'<asr_text>'}"
        return base

    def _infer_asr(
        self,
        contexts: List[str],
        wavs: List[np.ndarray],
        languages: List[Optional[str]],
    ) -> List[str]:
        """
        Run backend inference for chunk-level items.

        Args:
            contexts: List of context strings.
            wavs: List of mono waveforms (np.ndarray).
            languages: List of forced languages or None.

        Returns:
            List[str]: Raw decoded strings (one per chunk).
        """
        if self.backend == "transformers":
            return self._infer_asr_transformers(contexts, wavs, languages)
        if self.backend == "vllm":
            return self._infer_asr_vllm(contexts, wavs, languages)
        raise RuntimeError(f"Unknown backend: {self.backend}")

    def _infer_asr_transformers(
        self,
        contexts: List[str],
        wavs: List[np.ndarray],
        languages: List[Optional[str]],
    ) -> List[str]:
        outs: List[str] = []

        texts = [self._build_text_prompt(context=c, force_language=fl) for c, fl in zip(contexts, languages)]

        batch_size = self.max_inference_batch_size
        if batch_size is None or batch_size < 0:
            batch_size = len(texts)

        for i in range(0, len(texts), batch_size):
            sub_text = texts[i : i + batch_size]
            sub_wavs = wavs[i : i + batch_size]
            inputs = self.processor(text=sub_text, audio=sub_wavs, return_tensors="pt", padding=True)
            inputs = inputs.to(self.model.device).to(self.model.dtype)

            text_ids = self.model.generate(**inputs, max_new_tokens=self.max_new_tokens)

            decoded = self.processor.batch_decode(
                text_ids.sequences[:, inputs["input_ids"].shape[1]:],
                skip_special_tokens=True,
                clean_up_tokenization_spaces=False,
            )
            outs.extend(list(decoded))

        return outs

    def _infer_asr_vllm(
        self,
        contexts: List[str],
        wavs: List[np.ndarray],
        languages: List[Optional[str]],
    ) -> List[str]:
        inputs: List[Dict[str, Any]] = []
        for c, w, fl in zip(contexts, wavs, languages):
            prompt = self._build_text_prompt(context=c, force_language=fl)
            inputs.append({"prompt": prompt, "multi_modal_data": {"audio": [w]}})

        outs: List[str] = []
        for batch in chunk_list(inputs, self.max_inference_batch_size):
            outputs = self.model.generate(batch, sampling_params=self.sampling_params, use_tqdm=False)
            for o in outputs:
                outs.append(o.outputs[0].text)
        return outs

    def _resolve_alignment_language(
        self,
        predicted_languages: List[str],
        fallback_language: Optional[str],
    ) -> str:
        merged_language = merge_languages([l for l in predicted_languages if l])
        if merged_language:
            return merged_language.split(",")[0]
        if fallback_language:
            return fallback_language
        return "English"

    def _tokenize_alignment_text(self, text: str, language: str) -> List[str]:
        if self.forced_aligner is None:
            return []
        cleaned_text = str(text or "").strip()
        if not cleaned_text:
            return []
        lang = self._resolve_alignment_language([language], None)
        try:
            tokens, _ = self.forced_aligner.aligner_processor.encode_timestamp(cleaned_text, lang)
        except Exception:
            tokens = cleaned_text.split()
        return [str(t) for t in tokens if str(t).strip()]

    def _log_ground_truth_alignment(self, level: str, message: str) -> None:
        formatted = f"[Qwen3ASR][GTAlign] {message}"
        log_fn = getattr(logger, level, logger.info)
        log_fn(formatted)
        print(formatted)

    def _preview_text(self, text: str, limit: int = 32) -> str:
        text = str(text or "").replace("\n", " ").strip()
        if len(text) <= limit:
            return text
        return text[:limit] + "..."

    def _match_reference_window(
        self,
        predicted_tokens: List[str],
        reference_tokens: List[str],
        cursor: int,
        expected_center: Optional[float] = None,
        search_end: Optional[int] = None,
        must_cover: Optional[Tuple[int, int]] = None,
    ) -> Optional[Tuple[int, int, float]]:
        if not predicted_tokens:
            return (cursor, cursor, 1.0)
        if cursor >= len(reference_tokens):
            return None

        target_len = len(predicted_tokens)
        look_ahead = max(40, target_len * 3)
        hard_end = len(reference_tokens) - 1 if search_end is None else min(search_end, len(reference_tokens) - 1)
        max_start = min(hard_end, cursor + look_ahead)
        min_len = max(1, target_len - max(4, target_len // 2))
        max_len = min(len(reference_tokens), target_len + max(4, target_len // 2))

        best_span: Optional[Tuple[int, int]] = None
        best_score = float("-inf")

        for start in range(cursor, max_start + 1):
            local_max_len = min(max_len, len(reference_tokens) - start)
            local_min_len = min(min_len, local_max_len)
            for win_len in range(local_min_len, local_max_len + 1):
                end = start + win_len
                if must_cover is not None:
                    must_start, must_end = must_cover
                    if start > must_start or end < must_end:
                        continue
                candidate = reference_tokens[start : start + win_len]
                cand_center = start + (0.5 * win_len)
                score = SequenceMatcher(None, predicted_tokens, candidate, autojunk=False).ratio()
                score -= abs(win_len - target_len) * 0.01
                score -= (start - cursor) * 0.001
                if expected_center is not None:
                    score -= abs(cand_center - expected_center) * 0.01
                if score > best_score:
                    best_score = score
                    best_span = (start, start + win_len)

        if best_score < 0.2:
            return None
        return (best_span[0], best_span[1], best_score)

    def _split_text_into_alignment_sentences(
        self,
        text: str,
        language: str,
    ) -> List[Dict[str, Any]]:
        raw_text = str(text or "").strip()
        if not raw_text:
            return []

        terminators = set("。！？!?；;…\n")
        parts: List[str] = []
        current: List[str] = []
        for ch in raw_text:
            current.append(ch)
            if ch in terminators:
                part = "".join(current).strip()
                if part:
                    parts.append(part)
                current = []
        if current:
            part = "".join(current).strip()
            if part:
                parts.append(part)

        sentences: List[Dict[str, Any]] = []
        cursor = 0
        for part in parts:
            tokens = self._tokenize_alignment_text(part, language)
            if not tokens:
                continue
            start = cursor
            end = start + len(tokens)
            sentences.append(
                {
                    "text": part,
                    "tokens": tokens,
                    "start": start,
                    "end": end,
                }
            )
            cursor = end
        return sentences

    def _find_high_confidence_sentence_anchor(
        self,
        predicted_text: str,
        language: str,
        reference_sentences: List[Dict[str, Any]],
        min_sentence_idx: int,
        max_sentence_idx: Optional[int] = None,
    ) -> Optional[Dict[str, Any]]:
        predicted_sentences = self._split_text_into_alignment_sentences(predicted_text, language)
        if not predicted_sentences:
            return None

        if max_sentence_idx is None:
            max_sentence_idx = len(reference_sentences) - 1
        if min_sentence_idx > max_sentence_idx or min_sentence_idx >= len(reference_sentences):
            return None

        best: Optional[Dict[str, Any]] = None
        second_best_score = float("-inf")

        for pred_idx, pred_sentence in enumerate(predicted_sentences):
            pred_tokens = pred_sentence["tokens"]
            if len(pred_tokens) < 12:
                continue
            for ref_idx in range(min_sentence_idx, max_sentence_idx + 1):
                ref_sentence = reference_sentences[ref_idx]
                ref_tokens = ref_sentence["tokens"]
                if not ref_tokens:
                    continue
                score = SequenceMatcher(None, pred_tokens, ref_tokens, autojunk=False).ratio()
                len_ratio = min(len(pred_tokens), len(ref_tokens)) / max(len(pred_tokens), len(ref_tokens))
                score = score * 0.85 + len_ratio * 0.15
                if best is None or score > best["score"]:
                    if best is not None:
                        second_best_score = max(second_best_score, best["score"])
                    best = {
                        "pred_sentence_idx": pred_idx,
                        "pred_text": pred_sentence["text"],
                        "ref_sentence_idx": ref_idx,
                        "ref_start": ref_sentence["start"],
                        "ref_end": ref_sentence["end"],
                        "ref_text": ref_sentence["text"],
                        "score": score,
                    }
                else:
                    second_best_score = max(second_best_score, score)

        if best is None:
            return None

        margin = best["score"] - second_best_score if second_best_score > float("-inf") else best["score"]
        if best["score"] < 0.72 or margin < 0.08:
            return None
        best["margin"] = margin
        return best

    def _allocate_reference_spans_by_duration(
        self,
        token_count: int,
        durations: List[float],
    ) -> List[Tuple[int, int]]:
        return self._allocate_reference_spans_by_weights(token_count, durations)

    def _allocate_reference_spans_by_weights(
        self,
        token_count: int,
        weights: List[float],
        boundary_candidates: Optional[List[int]] = None,
    ) -> List[Tuple[int, int]]:
        if token_count <= 0:
            return [(0, 0) for _ in weights]
        total_weight = sum(max(0.0, w) for w in weights)
        if total_weight <= 0:
            total_weight = float(len(weights))
            weights = [1.0] * len(weights)

        boundaries = [0]
        cumulative = 0.0
        for weight in weights[:-1]:
            cumulative += max(0.0, weight)
            boundary = int(round((cumulative / total_weight) * token_count))
            if boundary_candidates:
                nearest = min(
                    boundary_candidates,
                    key=lambda cand: (abs(cand - boundary), cand),
                )
                if abs(nearest - boundary) <= max(12, token_count // 20):
                    boundary = nearest
            boundaries.append(boundary)
        boundaries.append(token_count)

        spans: List[Tuple[int, int]] = []
        for start, end in zip(boundaries[:-1], boundaries[1:]):
            start = max(0, min(start, token_count))
            end = max(start, min(end, token_count))
            spans.append((start, end))
        return spans

    def _log_alignment_sentences(
        self,
        debug_prefix: str,
        label: str,
        sentences: List[Dict[str, Any]],
    ) -> None:
        if not sentences:
            self._log_ground_truth_alignment(
                "info",
                f"{debug_prefix} {label} sentences=0.",
            )
            return
        for idx, sentence in enumerate(sentences):
            self._log_ground_truth_alignment(
                "info",
                f"{debug_prefix} {label}_sentence={idx} tokens={sentence['start']}:{sentence['end']} "
                f"text='{self._preview_text(sentence['text'], limit=96)}'.",
            )

    def _group_alignment_items_into_sentences(
        self,
        items: List[Any],
    ) -> List[Tuple[float, float, str]]:
        if not items:
            return []

        terminators = set("。！？!?；;…")
        grouped: List[Tuple[float, float, str]] = []
        current_text: List[str] = []
        current_start: Optional[float] = None
        current_end: Optional[float] = None

        for item in items:
            token_text = str(getattr(item, "text", "") or "").strip()
            if not token_text:
                continue
            if current_start is None:
                current_start = float(item.start_time)
            current_end = float(item.end_time)
            current_text.append(token_text)
            if any(ch in terminators for ch in token_text):
                grouped.append((current_start, current_end, "".join(current_text).strip()))
                current_text = []
                current_start = None
                current_end = None

        if current_text and current_start is not None and current_end is not None:
            grouped.append((current_start, current_end, "".join(current_text).strip()))

        return grouped

    def _log_aligned_result_sentences(
        self,
        sample_idx: int,
        chunk_idx: int,
        items: List[Any],
    ) -> None:
        for sentence_idx, (start_time, end_time, text) in enumerate(
            self._group_alignment_items_into_sentences(items)
        ):
            self._log_ground_truth_alignment(
                "info",
                f"sample={sample_idx} aligned_chunk={chunk_idx} sentence={sentence_idx} "
                f"time_range={round(start_time, 3)}-{round(end_time, 3)} "
                f"text='{self._preview_text(text, limit=96)}'.",
            )

    def _log_text_sentences_with_item_times(
        self,
        sample_idx: int,
        label: str,
        text: str,
        language: str,
        items: List[Any],
        chunk_idx: Optional[int] = None,
    ) -> None:
        sentences = self._split_text_into_alignment_sentences(text, language)
        if not sentences or not items:
            self._log_ground_truth_alignment(
                "info",
                f"sample={sample_idx} {label} sentence_count=0.",
            )
            return

        item_count = len(items)
        self._log_ground_truth_alignment(
            "info",
            f"sample={sample_idx} {label}{f'={chunk_idx}' if chunk_idx is not None else ''} sentence_count={len(sentences)}.",
        )
        for sentence_idx, sentence in enumerate(sentences):
            start_idx = max(0, min(int(sentence["start"]), item_count - 1))
            end_idx = max(start_idx + 1, min(int(sentence["end"]), item_count))
            start_time = float(items[start_idx].start_time)
            end_time = float(items[end_idx - 1].end_time)
            prefix = (
                f"sample={sample_idx} {label}={chunk_idx}"
                if chunk_idx is not None
                else f"sample={sample_idx} {label}"
            )
            self._log_ground_truth_alignment(
                "info",
                f"{prefix} sentence={sentence_idx} tokens={sentence['start']}:{sentence['end']} "
                f"time_range={round(start_time, 3)}-{round(end_time, 3)} "
                f"text='{self._preview_text(sentence['text'], limit=96)}'.",
            )

    def _require_text_alignment_dependencies(self, language: str) -> None:
        lang = self._resolve_alignment_language([language], None)
        missing: List[str] = []
        if rapidfuzz_fuzz is None:
            missing.append("rapidfuzz")
        if lang in ("Chinese", "Cantonese") and lazy_pinyin is None:
            missing.append("pypinyin")
        if missing:
            raise RuntimeError(
                "Ground-truth timestamp correction requires these Python packages to be installed "
                f"for {lang}: {', '.join(sorted(set(missing)))}."
            )

    def _normalize_numeric_text(self, text: str) -> str:
        return unicodedata.normalize("NFKC", str(text or ""))

    def _normalize_alignment_token_for_compare(
        self,
        token: str,
        language: str,
    ) -> str:
        lang = self._resolve_alignment_language([language], None)
        text = self._normalize_numeric_text(token)
        if not text:
            return ""
        text = _PUNCT_OR_SPACE_RE.sub("", text)
        if not text:
            return ""
        if lang in ("Chinese", "Cantonese"):
            if _CJK_RE.search(text) is None:
                return text.lower()
            pinyin_parts = lazy_pinyin(text, errors=lambda raw: [raw])
            pinyin = "".join(str(part) for part in pinyin_parts).lower()
            if pinyin:
                return pinyin
            raise RuntimeError(
                f"Failed to convert Chinese token to pinyin for alignment: {token!r}"
            )
        return text.lower()

    def _token_similarity(
        self,
        left: str,
        right: str,
    ) -> float:
        if not left or not right:
            return 0.0
        if left == right:
            return 1.0
        return float(rapidfuzz_fuzz.ratio(left, right)) / 100.0

    def _tokenize_ground_truth_with_original_text(
        self,
        text: str,
        language: str,
    ) -> List[Dict[str, str]]:
        tokens = self._tokenize_alignment_text(text, language)
        return [
            {
                "text": token,
                "norm": self._normalize_alignment_token_for_compare(token, language),
            }
            for token in tokens
        ]

    def _normalize_timed_items_for_compare(
        self,
        items: List[Any],
        language: str,
    ) -> List[Dict[str, Any]]:
        normalized: List[Dict[str, Any]] = []
        for idx, item in enumerate(items):
            token = str(getattr(item, "text", "") or "").strip()
            normalized.append(
                {
                    "index": idx,
                    "text": token,
                    "norm": self._normalize_alignment_token_for_compare(token, language),
                    "start_time": float(item.start_time),
                    "end_time": float(item.end_time),
                }
            )
        return normalized

    def _global_align_token_sequences(
        self,
        gt_tokens: List[Dict[str, str]],
        asr_tokens: List[Dict[str, Any]],
    ) -> List[Optional[int]]:
        n = len(gt_tokens)
        m = len(asr_tokens)
        if n == 0:
            return []
        if m == 0:
            return [None] * n

        gap_penalty = -0.65
        scores = np.zeros((n + 1, m + 1), dtype=np.float32)
        trace = np.zeros((n + 1, m + 1), dtype=np.int8)

        for i in range(1, n + 1):
            scores[i, 0] = scores[i - 1, 0] + gap_penalty
            trace[i, 0] = 1
        for j in range(1, m + 1):
            scores[0, j] = scores[0, j - 1] + gap_penalty
            trace[0, j] = 2

        similarity = np.zeros((n, m), dtype=np.float32)
        for i in range(n):
            gt_norm = gt_tokens[i]["norm"]
            for j in range(m):
                sim = self._token_similarity(gt_norm, asr_tokens[j]["norm"])
                similarity[i, j] = sim
                diag = scores[i, j] + (sim * 2.0 - 0.7)
                up = scores[i, j + 1] + gap_penalty
                left = scores[i + 1, j] + gap_penalty
                if diag >= up and diag >= left:
                    scores[i + 1, j + 1] = diag
                    trace[i + 1, j + 1] = 0
                elif up >= left:
                    scores[i + 1, j + 1] = up
                    trace[i + 1, j + 1] = 1
                else:
                    scores[i + 1, j + 1] = left
                    trace[i + 1, j + 1] = 2

        mapping: List[Optional[int]] = [None] * n
        i = n
        j = m
        while i > 0 or j > 0:
            move = trace[i, j] if i >= 0 and j >= 0 else 0
            if i > 0 and j > 0 and move == 0:
                sim = float(similarity[i - 1, j - 1])
                if sim >= 0.55:
                    mapping[i - 1] = j - 1
                i -= 1
                j -= 1
            elif i > 0 and (j == 0 or move == 1):
                i -= 1
            else:
                j -= 1

        return mapping

    def _interpolate_ground_truth_token_times(
        self,
        gt_tokens: List[Dict[str, str]],
        asr_tokens: List[Dict[str, Any]],
        mapping: List[Optional[int]],
    ) -> List[Tuple[float, float]]:
        if not gt_tokens:
            return []
        if not asr_tokens:
            return [(0.0, 0.0)] * len(gt_tokens)

        total_start = float(asr_tokens[0]["start_time"])
        total_end = float(asr_tokens[-1]["end_time"])
        if total_end <= total_start:
            total_end = total_start + (0.01 * len(gt_tokens))

        centers: List[Optional[float]] = [None] * len(gt_tokens)

        for idx, asr_idx in enumerate(mapping):
            if asr_idx is None:
                continue
            token = asr_tokens[asr_idx]
            centers[idx] = 0.5 * (token["start_time"] + token["end_time"])

        matched = [idx for idx, asr_idx in enumerate(mapping) if asr_idx is not None]
        if not matched:
            span = total_end - total_start
            if len(gt_tokens) == 1:
                return [(round(total_start, 3), round(total_end, 3))]
            centers = [
                total_start + (span * ((idx + 0.5) / len(gt_tokens)))
                for idx in range(len(gt_tokens))
            ]
        else:
            first = matched[0]
            first_center = float(centers[first])
            for idx in range(first - 1, -1, -1):
                ratio = (idx + 1) / float(first + 1)
                centers[idx] = total_start + ((first_center - total_start) * ratio)

            last = matched[-1]
            last_center = float(centers[last])
            suffix_span = len(gt_tokens) - last
            for idx in range(last + 1, len(gt_tokens)):
                ratio = (idx - last) / float(max(1, suffix_span))
                centers[idx] = last_center + ((total_end - last_center) * ratio)

            for left, right in zip(matched, matched[1:]):
                if right - left <= 1:
                    continue
                left_center = float(centers[left])
                right_center = float(centers[right])
                span = right - left
                for idx in range(left + 1, right):
                    ratio = (idx - left) / span
                    centers[idx] = left_center + ((right_center - left_center) * ratio)

        concrete_centers = [float(c) if c is not None else total_start for c in centers]
        boundaries: List[float] = [total_start]
        for idx in range(1, len(concrete_centers)):
            boundaries.append(0.5 * (concrete_centers[idx - 1] + concrete_centers[idx]))
        boundaries.append(total_end)

        min_step = 0.001
        max_boundary = total_end
        for idx in range(len(boundaries) - 1, -1, -1):
            lower_bound = total_start + (min_step * idx)
            upper_bound = max_boundary
            boundaries[idx] = min(max(boundaries[idx], lower_bound), upper_bound)
            max_boundary = boundaries[idx] - min_step

        out_times: List[Tuple[float, float]] = []
        for idx in range(len(gt_tokens)):
            start_time = boundaries[idx]
            end_time = boundaries[idx + 1]
            if end_time <= start_time:
                end_time = start_time + min_step
            out_times.append((round(start_time, 3), round(end_time, 3)))

        return out_times

    def _build_result_from_token_times(
        self,
        gt_tokens: List[Dict[str, str]],
        token_times: List[Tuple[float, float]],
        prototype_result: Any,
    ) -> Any:
        if prototype_result is None or not gt_tokens:
            return None
        item_type = type(prototype_result.items[0]) if getattr(prototype_result, "items", None) else None
        if item_type is None:
            return type(prototype_result)(items=[])
        items = []
        for token, (start_time, end_time) in zip(gt_tokens, token_times):
            items.append(
                item_type(
                    text=token["text"],
                    start_time=start_time,
                    end_time=end_time,
                )
            )
        return type(prototype_result)(items=items)

    def _log_token_alignment_debug(
        self,
        sample_idx: int,
        gt_tokens: List[Dict[str, str]],
        asr_tokens: List[Dict[str, Any]],
        mapping: List[Optional[int]],
    ) -> None:
        matched_count = sum(1 for item in mapping if item is not None)
        unmatched_count = len(mapping) - matched_count
        self._log_ground_truth_alignment(
            "info",
            f"sample={sample_idx} global_token_alignment gt_tokens={len(gt_tokens)} asr_tokens={len(asr_tokens)} "
            f"matched={matched_count} unmatched={unmatched_count}.",
        )

    def _align_reference_to_asr_timestamps(
        self,
        reference_text: str,
        language: str,
        asr_aligned_results: List[Any],
        sample_idx: int,
    ) -> Optional[Any]:
        self._require_text_alignment_dependencies(language)
        merged_asr = self._merge_align_results(asr_aligned_results)
        if merged_asr is None or not getattr(merged_asr, "items", None):
            return None

        asr_items = list(merged_asr.items)
        gt_tokens = self._tokenize_ground_truth_with_original_text(reference_text, language)
        asr_tokens = self._normalize_timed_items_for_compare(asr_items, language)
        mapping = self._global_align_token_sequences(gt_tokens, asr_tokens)
        self._log_token_alignment_debug(sample_idx, gt_tokens, asr_tokens, mapping)
        token_times = self._interpolate_ground_truth_token_times(gt_tokens, asr_tokens, mapping)
        result = self._build_result_from_token_times(gt_tokens, token_times, merged_asr)
        return result

    def _split_reference_text_by_chunks(
        self,
        predicted_chunk_texts: List[str],
        reference_text: str,
        language: str,
        chunk_durations: List[float],
    ) -> List[str]:
        debug_prefix = f"lang={language} chunks={len(predicted_chunk_texts)}"
        reference_tokens = self._tokenize_alignment_text(reference_text, language)
        reference_sentences = self._split_text_into_alignment_sentences(reference_text, language)
        predicted_token_groups = [
            self._tokenize_alignment_text(chunk_text, language) for chunk_text in predicted_chunk_texts
        ]
        predicted_sentences_by_chunk = [
            self._split_text_into_alignment_sentences(chunk_text, language)
            for chunk_text in predicted_chunk_texts
        ]
        sentence_boundaries = sorted(
            {
                0,
                len(reference_tokens),
                *[sentence["start"] for sentence in reference_sentences],
                *[sentence["end"] for sentence in reference_sentences],
            }
        )

        if not reference_tokens:
            self._log_ground_truth_alignment(
                "warning",
                f"{debug_prefix} reference tokenization produced 0 tokens; all chunk references will be empty.",
            )
            return [""] * len(predicted_chunk_texts)

        self._log_alignment_sentences(debug_prefix, "reference", reference_sentences)
        for idx, sentences in enumerate(predicted_sentences_by_chunk):
            self._log_alignment_sentences(f"{debug_prefix} chunk={idx}", "predicted", sentences)

        if sum(len(tokens) for tokens in predicted_token_groups) == 0:
            fallback_weights = [max(1.0, len(str(t or "").strip())) for t in predicted_chunk_texts]
            spans = self._allocate_reference_spans_by_weights(
                len(reference_tokens),
                fallback_weights,
                boundary_candidates=sentence_boundaries,
            )
            self._log_ground_truth_alignment(
                "warning",
                f"{debug_prefix} anchor ASR produced 0 usable tokens; falling back to text-length split across {len(reference_tokens)} reference tokens.",
            )
            return [
                " ".join(reference_tokens[start:end]).strip()
                for start, end in spans
            ]

        chunk_count = len(predicted_chunk_texts)
        sentence_anchors: List[Optional[Dict[str, Any]]] = [None] * chunk_count
        if reference_sentences:
            ref_sentence_cursor = 0
            for idx, predicted_text in enumerate(predicted_chunk_texts):
                anchor = self._find_high_confidence_sentence_anchor(
                    predicted_text=predicted_text,
                    language=language,
                    reference_sentences=reference_sentences,
                    min_sentence_idx=ref_sentence_cursor,
                )
                if anchor is None:
                    continue
                sentence_anchors[idx] = anchor
                ref_sentence_cursor = anchor["ref_sentence_idx"] + 1
                self._log_ground_truth_alignment(
                    "info",
                    f"{debug_prefix} chunk={idx} sentence_anchor={anchor['ref_start']}:{anchor['ref_end']} "
                    f"score={round(anchor['score'], 4)} margin={round(anchor['margin'], 4)} "
                    f"pred_sentence='{self._preview_text(anchor['pred_text'])}' ref_sentence='{self._preview_text(anchor['ref_text'])}'.",
                )

        anchor_spans: List[Optional[Tuple[int, int]]] = [None] * chunk_count
        anchor_scores: List[Optional[float]] = [None] * chunk_count
        anchor_expected_centers: List[Optional[float]] = [None] * chunk_count
        cursor = 0
        total_duration = sum(max(0.0, d) for d in chunk_durations)
        if total_duration <= 0:
            total_duration = float(max(1, chunk_count))
            duration_weights = [1.0] * chunk_count
        else:
            duration_weights = [max(0.0, d) for d in chunk_durations]
        cumulative_time = 0.0

        for idx, predicted_tokens in enumerate(predicted_token_groups):
            duration = duration_weights[idx]
            expected_center = (
                len(reference_tokens) * ((cumulative_time + (0.5 * duration)) / total_duration)
                if total_duration > 0
                else None
            )
            anchor_expected_centers[idx] = expected_center
            cumulative_time += duration
            if not predicted_tokens:
                continue
            target_len = len(predicted_tokens)
            next_sentence_anchor = None
            for future_idx in range(idx + 1, chunk_count):
                if sentence_anchors[future_idx] is not None:
                    next_sentence_anchor = sentence_anchors[future_idx]
                    break
            search_end = None
            must_cover = None
            if next_sentence_anchor is not None:
                search_end = next_sentence_anchor["ref_start"] + max(8, target_len // 2)
            if sentence_anchors[idx] is not None:
                must_cover = (sentence_anchors[idx]["ref_start"], sentence_anchors[idx]["ref_end"])
                local_search_end = sentence_anchors[idx]["ref_end"] + max(24, target_len)
                search_end = local_search_end if search_end is None else min(search_end, local_search_end)
            match = self._match_reference_window(
                predicted_tokens,
                reference_tokens,
                cursor,
                expected_center=expected_center,
                search_end=search_end,
                must_cover=must_cover,
            )
            if match is None:
                self._log_ground_truth_alignment(
                    "warning",
                    f"{debug_prefix} chunk={idx} anchor match failed after cursor={cursor}; "
                    f"expected_center={round(expected_center, 1) if expected_center is not None else 'n/a'} "
                    f"pred_tokens={len(predicted_tokens)} pred_preview='{self._preview_text(predicted_chunk_texts[idx])}'.",
                )
                continue

            start, end, score = match
            start = max(start, cursor)
            end = max(end, start)
            anchor_spans[idx] = (start, end)
            anchor_scores[idx] = score
            cursor = end
            self._log_ground_truth_alignment(
                "info",
                f"{debug_prefix} chunk={idx} anchor_span={start}:{end} anchor_tokens={end - start} "
                f"score={round(score, 4)} expected_center={round(expected_center, 1) if expected_center is not None else 'n/a'} "
                f"actual_center={round((start + end) * 0.5, 1)} pred_preview='{self._preview_text(predicted_chunk_texts[idx])}'.",
            )

        anchor_indices = [idx for idx, span in enumerate(anchor_spans) if span is not None]
        if not anchor_indices:
            fallback_weights = [
                max(1.0, float(len(tokens)))
                for tokens in predicted_token_groups
            ]
            spans = self._allocate_reference_spans_by_weights(
                len(reference_tokens),
                fallback_weights,
                boundary_candidates=sentence_boundaries,
            )
            self._log_ground_truth_alignment(
                "warning",
                f"{debug_prefix} no chunk anchors matched; using token-count split across {len(reference_tokens)} reference tokens. "
                f"chunk_weights={[len(tokens) for tokens in predicted_token_groups]}.",
            )
            return [
                " ".join(reference_tokens[start:end]).strip()
                for start, end in spans
            ]

        centers: List[float] = [0.0] * chunk_count
        first_anchor_idx = anchor_indices[0]
        first_anchor = anchor_spans[first_anchor_idx]
        assert first_anchor is not None
        first_center = 0.5 * (first_anchor[0] + first_anchor[1])

        prefix_durations = [max(0.0, d) for d in chunk_durations[: first_anchor_idx + 1]]
        prefix_total = sum(prefix_durations) or float(first_anchor_idx + 1)
        cumulative = 0.0
        for idx in range(first_anchor_idx + 1):
            cumulative += prefix_durations[idx] if sum(prefix_durations) > 0 else 1.0
            centers[idx] = first_center * (cumulative / prefix_total)

        for left_idx, right_idx in zip(anchor_indices, anchor_indices[1:]):
            left_anchor = anchor_spans[left_idx]
            right_anchor = anchor_spans[right_idx]
            assert left_anchor is not None and right_anchor is not None
            left_center = 0.5 * (left_anchor[0] + left_anchor[1])
            right_center = 0.5 * (right_anchor[0] + right_anchor[1])
            segment_durations = [max(0.0, d) for d in chunk_durations[left_idx : right_idx + 1]]
            segment_total = sum(segment_durations) or float(right_idx - left_idx + 1)
            cumulative = 0.0
            for idx in range(left_idx, right_idx + 1):
                if idx == left_idx:
                    centers[idx] = left_center
                    continue
                cumulative += segment_durations[idx - left_idx - 1] if sum(segment_durations) > 0 else 1.0
                ratio = cumulative / segment_total
                centers[idx] = left_center + (right_center - left_center) * ratio

        last_anchor_idx = anchor_indices[-1]
        last_anchor = anchor_spans[last_anchor_idx]
        assert last_anchor is not None
        last_center = 0.5 * (last_anchor[0] + last_anchor[1])
        suffix_durations = [max(0.0, d) for d in chunk_durations[last_anchor_idx:]]
        suffix_total = sum(suffix_durations) or float(chunk_count - last_anchor_idx)
        cumulative = 0.0
        for idx in range(last_anchor_idx, chunk_count):
            if idx == last_anchor_idx:
                centers[idx] = last_center
                continue
            cumulative += suffix_durations[idx - last_anchor_idx - 1] if sum(suffix_durations) > 0 else 1.0
            ratio = cumulative / suffix_total
            centers[idx] = last_center + (len(reference_tokens) - last_center) * ratio

        boundaries: List[int] = [0]
        for idx in range(1, chunk_count):
            boundary = int(round((centers[idx - 1] + centers[idx]) * 0.5))
            boundaries.append(boundary)
        boundaries.append(len(reference_tokens))

        spans: List[Tuple[int, int]] = []
        prev_end = 0
        for idx in range(chunk_count):
            start = max(prev_end, min(boundaries[idx], len(reference_tokens)))
            end = max(start, min(boundaries[idx + 1], len(reference_tokens)))
            spans.append((start, end))
            prev_end = end

        for idx in anchor_indices:
            anchor_start, anchor_end = anchor_spans[idx]
            start, end = spans[idx]
            if anchor_start < start:
                start = anchor_start
            if anchor_end > end:
                end = anchor_end
            spans[idx] = (start, end)

        fixed_spans: List[Tuple[int, int]] = []
        prev_end = 0
        for idx, (start, end) in enumerate(spans):
            start = max(prev_end, min(start, len(reference_tokens)))
            end = max(start, min(end, len(reference_tokens)))
            fixed_spans.append((start, end))
            prev_end = end
        if fixed_spans:
            fixed_spans[-1] = (fixed_spans[-1][0], len(reference_tokens))

        assigned_token_count = sum(max(0, end - start) for start, end in fixed_spans)
        self._log_ground_truth_alignment(
            "info",
            f"{debug_prefix} reference_tokens={len(reference_tokens)} anchor_chunks={len(anchor_indices)}/{chunk_count} "
            f"assigned_tokens={assigned_token_count}.",
        )
        if assigned_token_count != len(reference_tokens):
            self._log_ground_truth_alignment(
                "warning",
                f"{debug_prefix} coverage mismatch: assigned_tokens={assigned_token_count} reference_tokens={len(reference_tokens)}. "
                "This indicates some reference tokens were still not assigned to any chunk.",
            )

        chunk_ref_texts: List[str] = []
        for idx, (start, end) in enumerate(fixed_spans):
            ref_text = " ".join(reference_tokens[start:end]).strip()
            reason = "anchor" if anchor_spans[idx] is not None else "interpolated"
            score = anchor_scores[idx]
            if not ref_text:
                self._log_ground_truth_alignment(
                    "warning",
                    f"{debug_prefix} chunk={idx} final_span={start}:{end} tokens=0 reason={reason}; "
                    f"pred_tokens={len(predicted_token_groups[idx])} pred_preview='{self._preview_text(predicted_chunk_texts[idx])}'.",
                )
            else:
                self._log_ground_truth_alignment(
                    "info",
                    f"{debug_prefix} chunk={idx} final_span={start}:{end} tokens={end - start} reason={reason} "
                    f"score={score if score is not None else 'n/a'} expected_center={round(anchor_expected_centers[idx], 1) if anchor_expected_centers[idx] is not None else 'n/a'} "
                    f"pred_tokens={len(predicted_token_groups[idx])} "
                    f"pred_preview='{self._preview_text(predicted_chunk_texts[idx])}' ref_preview='{self._preview_text(ref_text)}'.",
                )
            chunk_ref_texts.append(ref_text)

        return chunk_ref_texts

    def _offset_align_result(self, result: Any, offset_sec: float) -> Any:
        """
        Apply time offset to a ForcedAlignResult-like object.

        This function assumes:
          - result has attribute `.items` which is a list of items with start_time/end_time in seconds.
          - dataclasses are frozen in upstream implementation, so we reconstruct by type.

        Args:
            result: ForcedAlignResult
            offset_sec: Offset in seconds

        Returns:
            ForcedAlignResult: New object with shifted timestamps.
        """
        if result is None:
            return None
        items = []
        for it in result.items:
            items.append(type(it)(text=it.text, 
                                  start_time=round(it.start_time + offset_sec, 3), 
                                  end_time=round(it.end_time + offset_sec, 3)))
        return type(result)(items=items)

    def _merge_align_results(self, results: List[Any]) -> Optional[Any]:
        """
        Merge multiple ForcedAlignResult objects into a single one by concatenating items.

        Args:
            results: List of ForcedAlignResult

        Returns:
            ForcedAlignResult or None
        """
        if not results:
            return None
        all_items = []
        for r in results:
            if r is None:
                continue
            all_items.extend(list(r.items))
        if not all_items:
            return None
        return type(results[0])(items=all_items)

    def init_streaming_state(
        self,
        context: str = "",
        language: Optional[str] = None,
        unfixed_chunk_num: int = 2,
        unfixed_token_num: int = 5,
        chunk_size_sec: float = 2.0,
    ) -> ASRStreamingState:
        """
        Initialize streaming ASR state for a single stream.

        Notes:
            - Streaming ASR is supported ONLY for vLLM backend.
            - Streaming ASR does NOT support timestamps (forced aligner is not used).
            - Batch inference is NOT supported.

        Args:
            context:
                Context string.
            language:
                Optional forced language. If provided, it must be in supported languages.
                Same behavior as transcribe(): forces text-only output via prompt suffix.
            unfixed_chunk_num:
                For the first N chunks, do not use previous output as prefix prompt (reset prefix to "").
            unfixed_token_num:
                Roll back the last K tokens from accumulated output when using it as prefix prompt
                after unfixed_chunk_num.
            chunk_size_sec:
                Chunk size in seconds (audio is 16k PCM). The function will internally convert it
                to sample count at 16kHz.

        Returns:
            ASRStreamingState: Mutable state object to be passed to streaming_transcribe() and
            finish_streaming_transcribe().

        Raises:
            ValueError:
                - If backend is not "vllm".
                - If chunk_size_sec <= 0.
                - If forced language is invalid (same validation rules as transcribe()).
        """
        if self.backend != "vllm":
            raise ValueError("Streaming ASR is supported only for vLLM backend (backend='vllm').")
        if chunk_size_sec is None or float(chunk_size_sec) <= 0:
            raise ValueError(f"chunk_size_sec must be > 0, got: {chunk_size_sec}")

        force_language = None
        if language is not None and str(language).strip() != "":
            ln = normalize_language_name(str(language))
            validate_language(ln)
            force_language = ln

        chunk_size_samples = int(round(float(chunk_size_sec) * SAMPLE_RATE))
        chunk_size_samples = max(1, chunk_size_samples)

        prompt_raw = self._build_text_prompt(context=context, force_language=force_language)

        return ASRStreamingState(
            unfixed_chunk_num=int(unfixed_chunk_num),
            unfixed_token_num=int(unfixed_token_num),
            chunk_size_sec=float(chunk_size_sec),
            chunk_size_samples=int(chunk_size_samples),
            chunk_id=0,
            buffer=np.zeros((0,), dtype=np.float32),
            audio_accum=np.zeros((0,), dtype=np.float32),
            prompt_raw=prompt_raw,
            context=context or "",
            force_language=force_language,
            language="",
            text="",
            _raw_decoded="",
        )

    def streaming_transcribe(self, pcm16k: np.ndarray, state: ASRStreamingState) -> ASRStreamingState:
        """
        Streaming ASR decode step.

        This function accepts an arbitrary-length 16k PCM float numpy array (mono).
        It buffers incoming samples, and whenever enough samples are accumulated to form one
        full chunk (chunk_size_sec), it runs one incremental decode step and updates:

          - state.language
          - state.text

        The caller only needs to keep passing audio to this function and read state.language/state.text.

        Implementation details:
            - Each time a new chunk is ready, we append it to audio_accum and re-feed *all* audio seen
              so far to the model (no padding).
            - We update the prompt as: state.prompt_raw + prefix_text
            - Prefix rollback strategy:
                * If chunk_id < unfixed_chunk_num: prefix_text = ""
                * Else: rollback last unfixed_token_num tokens from previously accumulated decoded text.

        Notes:
            - vLLM backend only.
            - No timestamps.
            - Single stream only (no batching).

        Args:
            pcm16k:
                16kHz mono PCM waveform (np.ndarray). Length can be any non-negative integer.
                dtype can be float32/float64/int16; it will be converted to float32.
            state:
                Streaming state returned by init_streaming_state().

        Returns:
            ASRStreamingState: The same state object (mutated) for convenience.

        Raises:
            ValueError:
                If backend is not "vllm" or state is invalid.
        """
        if self.backend != "vllm":
            raise ValueError("streaming_transcribe() is supported only for vLLM backend (backend='vllm').")
        if state is None:
            raise ValueError("state must not be None. Call init_streaming_state() first.")
        if pcm16k is None:
            raise ValueError("pcm16k must not be None.")

        # Ensure 1D mono
        x = np.asarray(pcm16k)
        if x.ndim != 1:
            x = x.reshape(-1)

        # Convert to float32 PCM in [-1, 1] if int16 provided
        if x.dtype == np.int16:
            x = (x.astype(np.float32) / 32768.0)
        else:
            x = x.astype(np.float32, copy=False)

        # Append to buffer
        if x.shape[0] > 0:
            state.buffer = np.concatenate([state.buffer, x], axis=0)

        # Consume full chunks
        while state.buffer.shape[0] >= state.chunk_size_samples:
            chunk = state.buffer[: state.chunk_size_samples]
            state.buffer = state.buffer[state.chunk_size_samples :]

            # Accumulate audio (re-feed from start, no padding)
            if state.audio_accum.shape[0] == 0:
                state.audio_accum = chunk
            else:
                state.audio_accum = np.concatenate([state.audio_accum, chunk], axis=0)

            # Build prefix with rollback strategy
            prefix = ""
            if state.chunk_id < state.unfixed_chunk_num:
                prefix = ""
            else:
                cur_ids = self.processor.tokenizer.encode(state._raw_decoded)
                k = int(state.unfixed_token_num)
                while True:
                    end_idx = max(0, len(cur_ids) - k)
                    prefix = self.processor.tokenizer.decode(cur_ids[:end_idx]) if end_idx > 0 else ""
                    if '\ufffd' not in prefix:
                        break
                    else:
                        if end_idx == 0:
                            prefix = ""
                            break
                        k += 1

            prompt = state.prompt_raw + prefix

            # vLLM input: single item
            inp = {"prompt": prompt, "multi_modal_data": {"audio": [state.audio_accum]}}

            outputs = self.model.generate([inp], sampling_params=self.sampling_params, use_tqdm=False)
            gen_text = outputs[0].outputs[0].text

            # Accumulate raw decoded (then parse to lang/text)
            state._raw_decoded = (prefix + gen_text) if prefix is not None else gen_text

            lang, txt = parse_asr_output(state._raw_decoded, user_language=state.force_language)
            state.language = lang
            state.text = txt

            state.chunk_id += 1

        return state

    def finish_streaming_transcribe(self, state: ASRStreamingState) -> ASRStreamingState:
        """
        Finish streaming ASR.

        This function flushes the remaining buffered audio in state.buffer (tail audio).
        It sends the remaining samples to the model even if shorter than chunk_size_sec,
        without padding. Then it updates state.language/state.text one last time.

        Notes:
            - vLLM backend only.
            - No timestamps.
            - Single stream only.

        Args:
            state:
                Streaming state.

        Returns:
            ASRStreamingState: Updated state (mutated).

        Raises:
            ValueError:
                If backend is not "vllm" or state is invalid.
        """
        if self.backend != "vllm":
            raise ValueError("finish_streaming_transcribe() is supported only for vLLM backend (backend='vllm').")
        if state is None:
            raise ValueError("state must not be None.")

        # If no remaining buffer, still return state as-is.
        if state.buffer is None or state.buffer.shape[0] == 0:
            return state

        tail = state.buffer
        state.buffer = np.zeros((0,), dtype=np.float32)

        # Append tail to accumulated audio
        if state.audio_accum.shape[0] == 0:
            state.audio_accum = tail
        else:
            state.audio_accum = np.concatenate([state.audio_accum, tail], axis=0)

        # Prefix rollback strategy (same as per-chunk)
        prefix = ""
        if state.chunk_id < state.unfixed_chunk_num:
            prefix = ""
        else:
            cur_ids = self.processor.tokenizer.encode(state._raw_decoded)
            end_idx = max(1, len(cur_ids) - int(state.unfixed_token_num))
            prefix = self.processor.tokenizer.decode(cur_ids[:end_idx])

        prompt = state.prompt_raw + prefix
        inp = {"prompt": prompt, "multi_modal_data": {"audio": [state.audio_accum]}}

        outputs = self.model.generate([inp], sampling_params=self.sampling_params, use_tqdm=False)
        gen_text = outputs[0].outputs[0].text

        state._raw_decoded = (prefix + gen_text) if prefix is not None else gen_text
        lang, txt = parse_asr_output(state._raw_decoded, user_language=state.force_language)
        state.language = lang
        state.text = txt

        state.chunk_id += 1
        return state
